import json
import csv
import urllib.request

def request(action, **params):
    """formats input """
    return {'action': action, 'params': params, 'version': 6}

def invoke(action, **params):
    """original fucntion from the connect website"""
    requestJson = json.dumps(request(action, **params)).encode('utf-8')
    #print(requestJson)
    response = json.load(urllib.request.urlopen(urllib.request.Request('http://localhost:8765', requestJson)))
    if len(response) != 2:
        raise Exception('response has an unexpected number of fields')
    if 'error' not in response:
        raise Exception('response is missing required error field')
    if 'result' not in response:
        raise Exception('response is missing required result field')
    if response['error'] is not None:
        raise Exception(response['error'])
    return response['result']

def invokejson(requestJsonob):
    """ updated function to use directly an json formatted object, generated by param_creator function , instead of an classical python dict"""

    requestJsonob = json.dumps(requestJsonob).encode('utf-8')
    #print(requestJsonob)
    response = json.load(urllib.request.urlopen(urllib.request.Request('http://localhost:8765', requestJsonob)))
    if len(response) != 2:
        raise Exception('response has an unexpected number of fields')
    if 'error' not in response:
        raise Exception('response is missing required error field')
    if 'result' not in response:
        raise Exception('response is missing required result field')
    if response['error'] is not None:
        raise Exception(response['error'])


    return response['result']



def note_creator(deckName, modelName, front, back):
    """ creates the object for a single note (card) in anki, all params MUST be specified, otherwise it does not work"""
    note = {
        "deckName": deckName,
        "modelName": modelName,
        "fields": {
            "Front": "{}".format(front),
            "Back": "{}".format(back)
        }
    }
    #print("iam the note", note)
    return note

def param_creator(action, version, deckName, modelName, csvfile):
    """ creates the whole object to give the invokejson function"""
    obj = {
        "action": action,
        "version": version,
        "params": {
            "notes": []
                }
    }
    with open(csvfile) as csvfile:
        reader = csv.reader(csvfile, delimiter='\t')
        for row in reader:
            #print(row)
            #print("iam the dic",obj["params"]["notes"])
            obj["params"]["notes"].append(note_creator(deckName, modelName, front=row[0], back=row[1]))
    #print(obj)
    return obj

def execution_addNotes(csvfile, deckName="verbforms", action="addNotes", version= 6,  modelName="Basic"):
    """wrapping function to generate new anki cards directly form a CSVfile"""
    try:
        invoke('createDeck', deck=deckName)
        new_ankicards_jsonformat = param_creator(action=action, version=version, deckName=deckName, modelName=modelName,
                                                 csvfile=csvfile)
        invokejson(new_ankicards_jsonformat)
        print("i did it")
    except urllib.error.URLError:
        print("Could not connect to anki server, please make sure anki is open")




if __name__ == "__main__":
    print(invoke("modelNames"))

    #invoke('createDeck', deck='test2')
    #print(invokejson(notetest_Web))
    #print(invokejson(guitest))

    #newnote = note_creator("new","basic", "unic", "horn")
    #result = invoke('deckNames')
    #print('got list of decks: {}'.format(result))

    #new_notes = param_creator()
    #invokejson(notetest_Web)

    execution_addNotes("test.tsv", modelName='verbformmodel ')